name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=main.py --cov=src tests/

      - name: Check test coverage
        run: |
          uv run coverage report --fail-under=80